### PR TITLE
Add finalizer to medata 

### LINKED ISSUE #391: add support for finalizers in metadata.
### Description

we recently had a use case of migration from one appset to another and needed an ability to set a finalizer on the appset 

### Potential Terraform Configuration

```hcl
resource "argocd_application_set" "services-test" {
  metadata {
    name = "appsetname"
    finalizers = [
    - final
    ]
  }


  spec {
    generator {
      git {
        repo_url = "server"
        revision = "master"

        file {
          path = "clusters/*/*/*/values.yaml"
        }
      }
    }

    template {
      metadata {
        name = "{{path[3]}}-{{path[2]}}"

        labels = {
          env = "{{path[1]}}"
        }
      }

      spec {
        project                = "default"
        revision_history_limit = 3

        source {
          repo_url        = "server"
          target_revision = "master"
          path            = "charts/"
          helm {
            release_name               = "{{path[3]}}"
            value_files                = ["values.yaml", "../../clusters/{{path[1]}}/{{path[2]}}/{{path[3]}}/values.yaml"]

            parameter {
              name  = "clusterName"
              value = "{{path[2]}}"
            }
          }
        }

        destination {
          name      = "{{path[2]}}"
          namespace = "{{path[3]}}"
        }

        sync_policy {
          sync_options = [
            "ServerSideApply=true",
            "CreateNamespace=true"
          ]
        }
      }
    }
  }
}

```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by KyriosGN0**
i have added finalizers as a medata element (used the same implementation that was in the application resource)
closes  #391

### CODE REVIEW

**Comment by KyriosGN0** [comment]
hi @oboukili @onematchfox, could someone take a look at this PR ? 
Thanks!

**Comment by KyriosGN0** [comment]
Not stale

**Comment by KyriosGN0** [comment]
Not stale

**Comment by onematchfox** [comment]
not stale

**Comment by KyriosGN0** [comment]
Reforked the repo, will reopen

**Pull request closed without merging**
